# Generated by Django 5.2.4 on 2025-07-30 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Abonnement 1 Mois, Abonnement Premium', max_length=100)),
                ('duree_jours', models.IntegerField(help_text="Durée de l'abonnement en jours (ex: 30 pour un mois)")),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actif', models.BooleanField(default=True, help_text='Si ce plan est actuellement disponible à la vente')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Affilie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_affiliation', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('solde_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('details_connexion', models.TextField(blank=True, help_text='Informations de connexion IPTV (lien M3U, etc.)', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.produit')),
            ],
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.ticketsupport')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
    ]
