# Generated by Django 5.2.5 on 2025-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_produit_actif_alter_produit_duree_jours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('actif', models.BooleanField(default=True, help_text='Seules les questions actives seront affichées sur le site public.')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Pour ordonner les questions. Celles avec un nombre plus petit apparaissent en premier.')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
